# Generated by Django 3.1.7 on 2021-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210327_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
