# Generated by Django 3.1.7 on 2021-03-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210327_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
