# Generated by Django 3.1.7 on 2021-03-27 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210327_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrammaticalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dictionaryEntry', models.ManyToManyField(related_name='grammatical_categories', to='api.DictionaryEntry')),
            ],
        ),
        migrations.DeleteModel(
            name='GramaticalCategory',
        ),
        migrations.DeleteModel(
            name='InternationalPhoneticAlphabet',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='word',
        ),
        migrations.AddField(
            model_name='definition',
            name='dictionaryEntry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='api.dictionaryentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thematiccategory',
            name='dictionaryEntry',
            field=models.ManyToManyField(related_name='thematic_categories', to='api.DictionaryEntry'),
        ),
    ]
