# Generated by Django 3.1.7 on 2021-03-27 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210327_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammaticalcategory',
            name='dictionaryEntry',
        ),
        migrations.RemoveField(
            model_name='thematiccategory',
            name='dictionaryEntry',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='grammaticalCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.grammaticalcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='thematicCategories',
            field=models.ManyToManyField(to='api.ThematicCategory'),
        ),
    ]
