# Generated by Django 3.1.7 on 2021-03-27 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210327_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryentry',
            old_name='grammaticalCategory',
            new_name='grammatical_category',
        ),
        migrations.RenameField(
            model_name='dictionaryentry',
            old_name='thematicCategories',
            new_name='thematic_categories',
        ),
    ]
