# Generated by Django 3.1.7 on 2021-03-27 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210327_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='dictionaryEntry',
            new_name='entry',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='grammatical_category',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='thematic_categories',
        ),
        migrations.AddField(
            model_name='grammaticalcategory',
            name='entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='grammatical_categories', to='api.dictionaryentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thematiccategory',
            name='entries',
            field=models.ManyToManyField(related_name='thematic_categories', to='api.DictionaryEntry'),
        ),
    ]
