# Generated by Django 3.1.7 on 2021-03-27 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210327_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grammaticalcategory',
            name='entry',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='grammatical_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entry', to='api.grammaticalcategory'),
            preserve_default=False,
        ),
    ]
