# Generated by Django 3.1.7 on 2021-03-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210328_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='example',
        ),
    ]
