# Generated by Django 3.1.7 on 2021-03-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_word_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='definition',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
