# Generated by Django 3.1.7 on 2021-03-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210328_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(1, 'Tati'), (2, 'Persian'), (3, 'English')], default=0)),
                ('position', models.IntegerField(choices=[(0, 'First'), (1, 'Second'), (2, 'Third'), (3, 'Fourth'), (4, 'Fifth')], default=0)),
                ('word', models.CharField(blank=True, default='', max_length=250)),
                ('definition', models.CharField(blank=True, default='', max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_items', to='api.dictionaryentry')),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
