# Generated by Django 3.1.7 on 2021-03-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210328_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryEquivalent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.IntegerField(choices=[(0, 'Persian'), (1, 'English')], default=0)),
                ('position', models.IntegerField(choices=[(0, 'First'), (1, 'Second'), (2, 'Third'), (3, 'Fourth'), (4, 'Fifth')], default=0)),
                ('word', models.CharField(blank=True, default='', max_length=250)),
                ('definition', models.CharField(blank=True, default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='tati_word',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='ipa',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='EntryItem',
        ),
        migrations.AddField(
            model_name='entryequivalent',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_equivalents', to='api.dictionaryentry'),
        ),
    ]
